TARGET = RAYTRACE

OBJS = bbox.o cr.o env.o fbuf.o geo.o huprn.o husetup.o hutv.o isect.o \
	main.o matrix.o memory.o poly.o raystack.o shade.o sph.o trace.o \
	tri.o workpool.o ../../inst/hook.c

include ../../Makefile.RISCV.config


bbox.c: bbox.c.in rt.h ../../inst/hook.c
cr.c:	cr.c.in rt.h ../../inst/hook.c
env.c:	env.c.in rt.h ../../inst/hook.c
fbuf.c: fbuf.c.in rt.h ../../inst/hook.c
geo.c:	geo.c.in rt.h ../../inst/hook.c
huprn.c: huprn.c.in rt.h ../../inst/hook.c
husetup.c: husetup.c.in rt.h ../../inst/hook.c
hutv.c: hutv.c.in rt.h ../../inst/hook.c
isect.c: isect.c.in rt.h ../../inst/hook.c
main.c: main.c.in rt.h ../../inst/hook.c
matrix.c: matrix.c.in rt.h ../../inst/hook.c
memory.c: memory.c.in rt.h ../../inst/hook.c
poly.c: poly.c.in rt.h ../../inst/hook.c
raystack.c: raystack.c.in rt.h ../../inst/hook.c
shade.c: shade.c.in rt.h ../../inst/hook.c
sph.c:	sph.c.in rt.h ../../inst/hook.c
trace.c: trace.c.in rt.h ../../inst/hook.c
tri.c:	tri.c.in rt.h ../../inst/hook.c
workpool.c: workpool.c.in rt.h ../../inst/hook.c